fresh_shop1/cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量的刷新
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 总计
    path('cart_price/', views.cart_price, name='cart_price'),
    # 修改购物车中的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),
    # 删除购物车中的商品
    path('del_cart/<int:id>/', views.del_cart, name='del_cart'),
]

fresh_shop1/fresh_shop/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from fresh_shop.settings import MEDIA_ROOT, MEDIA_URL
from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 导入应用
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('', views.index)
]
# 配置解析media文件的信息
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

fresh_shop1/goods/urls.py
from django.urls import path

from goods import views

urlpatterns = [
    # 首页
    path('index/', views.index, name='index'),
    path('detail/<int:id>/', views.detail, name='detail'),
    # 最近浏览记录
    path('recent_browse/', views.recent_browse, name='recent_browse'),
    path('goods_list/<int:id>/', views.goods_list, name='goods_list'),
]

fresh_shop1/order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    # 结算功能
    path('place_order/', views.place_order, name='place_order'),
    path('order/', views.order, name='order'),
]

fresh_shop1/user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('user_site/', views.user_site, name='user_site'),
    path('user_info/', views.user_info, name='user_info'),
    path('user_order/', views.user_order, name='user_order'),
]

fresh_shop1/cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

fresh_shop1/cart/views.py
from django.http import JsonResponse
from django.shortcuts import render

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品的id值和商品数量num
        # 组装存储商品的格式：[goods_id, num, is_select]
        # 组装多个商品的格式：[[goods_id, num, is_select],]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]
        session_goods = request.session.get('goods')
        if session_goods:
            # 1.添加的商品存在于购物车中，则修改
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False
            if flag:
                # 2.添加的商品不存在于购物车中，则新增
                session_goods.append(goods_list)
            request.session['goods'] = session_goods
            count = len(session_goods)

        else:
            # 第一次添加购物车
            # 需组装商品格式为[[goods_id, num, is_select],]
            request.session['goods'] = [goods_list]
            count = 1
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        if session_goods:
            count = len(session_goods)
        else:
            count = 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        result = []
        if session_goods:
            # 组装返回格式：[objects1,objects2...]
            # objects===> [Goods Objects, is_select, num, total_price]
            for se_goods in session_goods:
                # se_goods为[goods_id, num, is_select]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                total_price = goods.shop_price * se_goods[1]
                data = [goods, se_goods[1], se_goods[2], total_price]
                result.append(data)
        return render(request, 'cart.html', {'result': result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总的商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        for se_goods in session_goods:
            # se_goods为[goods_id, num, is_select]
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.shop_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code': 200,
                             'msg': '请求成功',
                             'all_total': all_total,
                             'all_price': all_price,
                             'is_select_num': is_select_num})


def change_cart(request):
    if request.method == 'POST':
        # 修改商品的数量和选择状态
        # 其实就是修改session中的商品信息，结果是[goods_id, num, is_select]
        # 1.获取商品id值和(数量或者选择状态)
        goods_id = request.POST.get('goods_id')
        if goods_id:
            goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        checkall = request.POST.get('checkall')
        if checkall == 'true':
            checkall = 1
        else:
            checkall = 0
        # 修改
        session_goods = request.session.get('goods')
        subtotal = 0
        if not goods_id:
            # 全选
            if checkall:
                for se_goods in session_goods:
                    if not se_goods[2]:
                        se_goods[2] = 1
            # 取消全选
            else:
                for se_goods in session_goods:
                    if se_goods[2]:
                        se_goods[2] = 0
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                if goods_num:
                    se_goods[1] = int(goods_num)
                    # 小计
                    subtotal = Goods.objects.get(pk=goods_id).shop_price * se_goods[1]
                # 修改选中状态
                if goods_select:
                    se_goods[2] = 0
                else:
                    se_goods[2] = 1
        # 保存修改
        request.session['goods'] = session_goods
        return JsonResponse({'code': 200, 'msg': '请求成功', 'subtotal': subtotal})


def del_cart(request, id):
    if request.method == 'POST':
        # 1.思路：通过传入的id值，去session中查找，查找到则删除数据
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            # se_goods结构为[goods_id, num, is_select]
            if se_goods[0] == id:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        # 删除数据库中购物车中的商品信息
        user_id = request.session.get('user_id')
        if user_id:
            ShoppingCart.objects.filter(goods_id=id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

fresh_shop1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}
    {% endblock %}

    {% block js1 %}
    {% endblock %}
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block search %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block footer %}
    {% endblock %}

    {% block js2 %}
    {% endblock %}
</body>
</html>

fresh_shop1/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
<link rel="stylesheet" type="text/css" href="/static/css/main.css">
{% endblock %}

{% block js1 %}
<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{% endblock %}

{% block header %}
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            <div class="login_info fl" {% if user.id %} style="display: block;" {% endif %}>
                欢迎您：<em>{{ user.username }}</em>
                <span>|</span>
                <a href="{% url 'user:logout' %}">退出</a>
            </div>
            <div class="login_btn fl" {% if user.id %} style="display: none;" {% endif %}>
                <a href="/user/login/">登录</a>
                <span>|</span>
                <a href="{% url 'user:register' %}">注册</a>
            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'user:user_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'user:user_order' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block search %}
<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="/cart/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
    <script>
        $.get('/cart/cart_num/', function(data){
            if(data.code == '200'){
                $('#show_count').text(data.count)
            }
        })
    </script>
	</div>
{% endblock %}

{% block footer %}
    <div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock  %}

fresh_shop1/templates/cart.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-购物车
{% endblock%}

{% block content%}
	<div class="total_count">全部商品<em>2</em>件</div>	
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
	{% for goods in result %}
	<ul class="cart_list_td clearfix" id="goods_{{ goods.0.id }}">
		<li class="col01"><input type="checkbox" name="" {% if goods.2 %}checked{% endif %} onclick="change_select({{ goods.0.id }});"></li>
		<li class="col02"><img src="/media/{{ goods.0.goods_front_image }}"></li>
		<li class="col03">{{ goods.0.name }}<br><em>{{ goods.0.shop_price }}</em></li>
		<li class="col04">500g</li>
		<li class="col05">{{ goods.0.shop_price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl" onclick="add_cart({{ goods.0.id }})">+</a>
				<input type="text" class="num_show fl" id="num_show_{{ goods.0.id }}" value="{{ goods.1 }}">
				<a href="javascript:;" class="minus fl" onclick="sub_cart({{ goods.0.id }})">-</a>
			</div>
		</li>
		<li class="col07">{{ goods.3 }}元</li>
		<li class="col08"><a href="javascript:;" onclick="del_cart({{ goods.0.id }});">删除</a></li>
	</ul>
	{% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" onclick="check_all();"></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
		<li class="col04"><a href="{% url 'order:place_order' %}">去结算</a></li>
	</ul>
{% csrf_token %}
<script>
	<!--全选-->
	function check_all(){
		var csrf = $('input[name="csrfmiddlewaretoken"]').val()
		var checkall = $('.settlements input').prop('checked')
		$.ajax({
			url: '/cart/change_cart/',
			type:'POST',
			data:{'checkall': checkall},
			headers:{'X-CSRFToken':csrf},
			dataType: 'json',
			success:function(data){
				if(checkall){
					$('.cart_list_td input').prop('checked', true)
					$('.settlements input').prop('checked', true)
				}else{
					$('.cart_list_td input').removeProp('checked')
					$('.settlements input').removeProp('checked')
				}
				cart_price()
			},
			error:function(data){
				alert('失败')
			}
		})
	}
	<!--改变选择状态-->
	function change_select(id){
		var csrf = $('input[name="csrfmiddlewaretoken"]').val()
		var select = $('#goods_'+id+' input').attr('checked')
		$.ajax({
			url: '/cart/change_cart/',
			type:'POST',
			data:{'goods_id': id, 'goods_select': select},
			headers:{'X-CSRFToken':csrf},
			dataType: 'json',
			success:function(data){
				if(select){
					$('#goods_'+id+' input').removeAttr('checked')
				}else{
					$('#goods_'+id+' input').attr('checked', 'checked')
				}
				cart_price()
			},
			error:function(data){
				alert('失败')
			}
		})
	}
	<!--刷新价格/件数-->
	function cart_price(){
		$.get('/cart/cart_price/', function(data){
			if(data.code == 200){
				$('.total_count em').html(data.all_total)
				$('.settlements .col03 em').html(data.all_price)
				$('.settlements .col03 b').html(data.is_select_num)
			}
		})
	}
	cart_price()
	<!--添加商品数量-->
	function add_cart(id){
		var num = $('#num_show_' + id).val()
		var new_num = parseInt(num) + 1
		$('#num_show_' + id).val(new_num)
		change_cart(id, new_num)
	}
	<!--减少商品数量-->
	function sub_cart(id){
		var num = $('#num_show_' + id).val()
		if(parseInt(num)>1){
			var new_num = parseInt(num) - 1
			$('#num_show_' + id).val(new_num)
			change_cart(id, new_num)
		}
	}
	<!--修改数量-->
	function change_cart(id, new_num){
		var csrf = $('input[name="csrfmiddlewaretoken"]').val()
		$.ajax({
			url: '/cart/change_cart/',
			type:'POST',
			data:{'goods_id': id, 'goods_num': new_num},
			headers:{'X-CSRFToken':csrf},
			dataType: 'json',
			success:function(data){
				<!--刷新数量、价格-->
				$('#goods_'+id+' .col07').text(data.subtotal+'元')
				cart_price()
			},
			error:function(data){
			}
		})
	}

	function del_cart(id){
		var csrf = $('input[name="csrfmiddlewaretoken"]').val()
		$.ajax({
			url: '/cart/del_cart/'+id+'/',
			type:'post',
			dataType:'json',
			headers:{'X-CSRFToken':csrf},
			success:function(data){
				<!--刷新整个页面-->
				<!--location.href='/cart/cart/'-->
				<!--移除ul元素-->
				$('#goods_'+id).remove()
				cart_price()
			},
			error:function(data){
				alert('失败')
			}
		})
	}
</script>
{% endblock %}

fresh_shop1/templates/index.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-首页
{% endblock %}

{% block js1 %}
	{{ block.super }}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for gc in result %}
			<li><a href="{% url 'goods:goods_list' gc.0.id %}" class="fruit">
				{% for gct in gcts %}
					{% if gct.0 == gc.0.category_type %}
						{{ gct.1 }}
					{% endif %}
				{% endfor %}
			</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>
{% for gc in result %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model01">
				{% for gct in gcts %}
					{% if gct.0 == gc.0.category_type %}
						{{ gct.1 }}
					{% endif %}
				{% endfor %}
			</h3>
			<!--<div class="subtitle fl">-->
				<!--<span>|</span>-->
				<!--<a href="#">鲜芒</a>-->
				<!--<a href="#">加州提子</a>-->
				<!--<a href="#">亚马逊牛油果</a>-->
			<!--</div>-->
			<a href="{% url 'goods:goods_list' gc.0.id %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>
		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{ gc.0.category_front_image }}"></div>
	<ul class="goods_list fl">
		{% for g in gc.1 %}
			<li>
				<h4><a href="{% url 'goods:detail' g.id %}">{{ g.name }}</a></h4>
				<a href="{% url 'goods:detail' g.id %}"><img src="/media/{{ g.goods_front_image }}"></a>
				<div class="prize">{{ g.shop_price }}</div>
			</li>
		{% endfor %}
	</ul>
		</div>
	</div>
{% endfor %}
{% endblock %}

{% block js2 %}

{% endblock %}
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>

fresh_shop1/templates/list.html
{% extends 'base_main.html' %}

{% block title %}
天天生鲜-商品列表
{% endblock %}

{% block content %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for gc in gcs %}
						<li><a href="{% url 'goods:goods_list' gc.id %}" class="fruit">
						{% for gct in gcts %}
							{% if gct.0 == gc.id %}
								{{ gct.1 }}
							{% endif %}
						{% endfor %}
						</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="/goods/index/">首页</a></li>
				<!--<li class="interval">|</li>-->
				<!--<li><a href="">手机生鲜</a></li>-->
				<!--<li class="interval">|</li>-->
				<!--<li><a href="">抽奖</a></li>-->
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">
			{% for gct in gcts %}
				{% if gct.0 == gc.id %}
					{{ gct.1 }}
				{% endif %}
			{% endfor %}
		</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
					<li>
						<a href="#"><img src="images/goods/goods001.jpg"></a>
						<h4><a href="#">进口柠檬</a></h4>
						<div class="prize">￥3.90</div>
					</li>
					<li>
						<a href="#"><img src="images/goods/goods002.jpg"></a>
						<h4><a href="#">玫瑰香葡萄</a></h4>
						<div class="prize">￥16.80</div>
					</li>
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="#" class="active">默认</a>
				<a href="#">价格</a>
				<a href="#">人气</a>
			</div>

			<ul class="goods_type_list clearfix">
				{% for g in goods %}
				<li>
					<a href="{% url 'goods:detail' g.id %}"><img src="/media/{{ g.goods_front_image }}"></a>
					<h4><a href="{% url 'goods:detail' g.id %}">{{ g.name }}</a></h4>
					<div class="operate">
						<span class="prize">{{ g.shop_price }}</span>
						<span class="unit">单位：500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if goods.has_previous %}
				<a href="{% url 'goods:goods_list' gc.id %}?page={{ goods.previous_page_number }}">上一页</a>
				{% endif %}
				{% for i in goods.paginator.page_range %}
				<a href="{% url 'goods:goods_list' gc.id %}?page={{ i }}">{{ i }}</a>
				{% endfor %}
				{% if goods.has_next %}
				<a href="{% url 'goods:goods_list' gc.id %}?page={{ goods.next_page_number }}">下一页></a>
				{% endif %}
			</div>
		</div>
	</div>
{% endblock %}

fresh_shop1/templates/user_center_info.html
{% extends 'base_main.html' %}
{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="{% url 'user:user_info' %}">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						{% for goods in goods_list %}
							<li>
								<a href="{% url 'goods:detail' goods.id %}"><img src="/media/{{ goods.goods_front_image }}"></a>
								<h4><a href="{% url 'goods:detail' goods.id %}">{{ goods.name }}</a></h4>
								<div class="operate">
									<span class="prize">{{ goods.shop_price }}</span>
									<span class="unit">单位：500g</span>
									<a class="add_goods" title="加入购物车" onclick="add_cart({{ goods.id }});"></a>
								</div>
								{% csrf_token %}
								<script>
									function add_cart(id){
										var num = 1
										var csrf = $('input[name="csrfmiddlewaretoken"]').val()
										$.ajax({
											url: '/cart/add_cart/',
											type: 'POST',
											data: {'goods_id': id, 'goods_num': num},
											headers: {'X-CSRFToken': csrf},
											dataType: 'json',
											success: function(data){
												location.href='/cart/cart/'
											},
											error: function(data){
												alert('失败')
											}
										})
									}
								</script>
							</li>
						{% endfor %}

			</ul>
		</div>
		</div>
	</div>

{% endblock %}

fresh_shop1/templates/user_center_order.html
{% extends 'base_main.html' %}


{% block title %}
天天生鲜-用户中心
{% endblock %}

{% block search %}
	<div class="search_bar clearfix">
		<a href="/goods/index/" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
{% endblock %}
{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			{% include 'base_user.html' %}
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{% for order in orders %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.add_time | date:"Y-m-d H:i:s" }}</li>
					<li class="col02" style="width:55%;">订单号：{{ order.order_sn }}</li>
					<li class="col02 stress">
						{% for s in status %}
							{% ifequal s.0 order.pay_status %}
								{{ s.1 }}
							{% endifequal %}
						{% endfor %}
					</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{% for order_goods in order.goods.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/{{ order_goods.goods.goods_front_image }}"></li>
									<li class="col02">{{ order_goods.goods.name }}<em>{{ order_goods.goods.shop_price }}/500g</em></li>
									<li class="col03">{{ order_goods.goods_nums }}</li>
									<li class="col04">{{ order_goods.goods.shop_price}}元</li>
								</ul>
								{% endfor %}
							</td>
							<td width="15%">{{ order.order_mount }}元</td>
							<td width="15%">
								{% for s in status %}
									{% ifequal s.0 order.pay_status %}
										{{ s.1 }}
									{% endifequal %}
								{% endfor %}</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}

				<div class="pagenation">
					{% if orders.has_previous %}
					<a href="{% url 'user:user_order' %}?page={{ orders.previous_page_number }}"><上一页</a>
					{% endif %}
					{% for i in orders.paginator.page_range %}
					<a href="{% url 'user:user_order' %}?page={{ i }}">{{ i }}</a>
					{% endfor %}
					{% if orders.has_next %}
					<a href="{% url 'user:user_order' %}?page={{ orders.next_page_number }}">下一页></a>
					{% endif %}
				</div>
		</div>
	</div>
{% endblock %}